version: '3'

services:

  db:
    image: postgres:12-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    volumes:
    - postgres

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SCHEMA: ${SCHEMA}
      JWT_KEY: ${JWT_KEY}
    ports:
      - 8080:8080

volumes:
  postgres: